### ISSUE TITLE
Review constructors.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-sdk#118]
Golang does not typically throw (panic). When it does panic in production, the container dies, the docker logs are gone, and debugging is difficult to say the least.

- Review all constructors in the sdk. (NewXXX, etc)
- Ensure parameters passed to a constructor are valid. If nil is valid, that's fine, but nil check the struct field when used.
- Add tests for invalid parameters.
- Add error check for constructor calls.
- Constructors should return (*Something, error) per https://stackoverflow.com/questions/34774615/should-a-constructor-function-return-an-error-or-a-null-value

**Comment by edaniszewski** [comment]
closing. a lot of this work has been done. will continue to apply this pattern with 1.0 changes.
