### ISSUE TITLE
Consider how to verify examples are functional via automation.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-sdk#135]
This is going to be a difficult one and could lead to being a ticket that never dies, but warrants discussion.

Currently our CI ensures that examples build, but does not demonstrate that they work. We need to eyeball them prior to release. It is highly important that our examples work when release, otherwise we look like we don't know what we're doing.

Consider how to automatically verify the functionality of examples.

Some options:
We should not see errors in the log.
We could write a test client to verify for each example. (This needs fleshing out and is highly example specific.)

**Comment by edaniszewski** [comment]
related: #198 

will add this to the 1.0 work items, since this should be feasible w/ command line support.
