### ISSUE TITLE
clean up logging

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#164]
a wave of logging updates were made to get better visibility into the SDK. A lot of the logging messages end up being duplicated because of err propagation and re-logging. Its better than having no logging, but it does make the logs cluttered and likely harder to read and find where the actual error is coming from.

we'll need to
- come up with a sane way to do logging so we don't end up with a ton of duplicate messages
- see about adding more context info to the log output (file/line number..)
- clean up log messages in general - make sure we give all the important info.. make sure we're not logging out pointer addresses (not useful), etc.

**Comment by MatthewHink** [comment]
FWIW: grep is your friend for weeding through logs. It is better to have too many logs to go through than nothing to debug.

That being said, it is worthwhile to make a cleanup pass.
