### ISSUE TITLE
design plugin auto-discovery

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#248]
had a brief conversation last week w/ @timfallmk and we agreed that it would be nice to have some sort of auto-discovery option for synse/plugins. 

v1.0 would be a good place to add that in, it seems to me. will need to do some more research into it and figure out use cases, etc.

**Comment by timfallmk** [comment]
@edaniszewki let’s come up with some plans sometime next week.

**Comment by edaniszewski** [comment]
no changes needed in the SDK for this - this will be something that needs to be addressed at the Synse Server level.
