### ISSUE TITLE
Duplicate ids are allowed

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-sdk#267]
Hit this with a bug in SNMP. A non-unique device id will overwrite an existing one without flagging anything.

Should consider a logger.warn, possibly even a hard error. Device registration currently returns an error on the first failure, so maybe that's the way to go (?)

**Comment by edaniszewski** [comment]
this is fixed in v1.0 with a hard error: https://github.com/vapor-ware/synse-sdk/blob/v1.0/sdk/devices.go#L424
