### ISSUE TITLE
support for bulk write

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#274]
this falls out of #270 

this will not be included in v1.0, since we have nothing that needs it. this will probably sit on the backburner until there is something that requires it.

**Comment by MatthewHink** [comment]
Need to find a use case for this.

**Comment by edaniszewski** [comment]
this is explicitly not supported in v3. bulk writes would make the transaction tracking process more difficult, but more importantly would make state resolution difficult to track for actions (e.g. what is a partial failure? would there have to be rollbacks?, ...). closing as won't fix.
