### ISSUE TITLE
Handler is tied to the device model. For configured devices this is fine. For dynamically discovered device It's not.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-sdk#280]
The problem is that the model is in all of the proto files.

Currently we can either lie about the model and make it common for all SNMP devices (sounds like a bad idea), or we can write separate handlers for each SNMP device model we support even if the different devices support the same SNMP MIBs.

In dreamland we tie the handlers to the SNMP MIB that we and the device support.

I would imagine that this check would be an issue for any dynamically discovered devices as well (IPMI).

Check in the SDK is here:
https://github.com/vapor-ware/synse-sdk/blob/04e36391a237efacf57bb0074b67a967cdf06705/sdk/devices.go#L79

**Comment by edaniszewski** [comment]
we should talk about this one sometime. handlers aren't tied to device model in sdk v1.0, but devices reference their handler by name (the name of the handler being arbitrary), so that hopefully should grant enough leeway to make it useful in the dynamic case (at least, that was the goal)

**Comment by edaniszewski** [comment]
handlers no longer tied to the model, and with the arbitrary name spacing for handlers, I believe this can be tied to the SNMP MIB, so I'm gonna call this fixed
