### ISSUE TITLE
How to differentiate power in watts and power in VA?

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-sdk#282]
- Same scan type (power) / different units.

Mostly need to figure out how this works.

Both devices should be power. Units are completey different.

Issue is the proto file and how these devices show up in a scan based on type.

**Comment by edaniszewski** [comment]
I'd need to go over a use case example to get a better understanding of the issue, but this may be fixed in sdk v1.0, since there are no proto files there anymore.
