### ISSUE TITLE
Deprecation notice: vaporio/golang:1.11 is being removed

### ISSUE THREAD

**Issue by marcoceppi** [vapor-ware/synse-sdk#436]
We have added support for 1.12 and 1.13 Golang images. Upstream Docker project has already removed support for building 1.11 images and we will be doing so as well. This repo makes use of 1.11 in either it's `.jenkins` or `Dockerfile` and should be updated and tested with either 1.12 or 1.13 of Golang.

**Comment by edaniszewski** [comment]
proposing to close -- the v3/staging branch (effective active HEAD) does not hold a reference to 1.11
