### ISSUE TITLE
do not apply transformations on a reading with nil value

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#468]
Since we allow reading values to be `nil`, and readings may have a transformer function applied to them (e.g.  scale by 10), what is the appropriate behavior when applying the transformer?

- should a `nil` value with transformer result in an error?
- should a `nil` value prevent the transformer from being run?
- something else?

The current implementation errors (option 1, above), but I feel like the correct thing to do may be to just prevent the transformer from running (option 2, above).

```
time="2020-05-05T14:33:35.602Z" level=error msg="[reading] error converting reading value to float64" value="<nil>"
time="2020-05-05T14:33:35.602Z" level=error msg="[scheduler] failed to apply reading transformer" device=e83295b1-4c4e-55b7-8233-34cab54b78ea error="unable to convert value <nil>, type <nil> to float64" info=upsBypassFrequency transformer="scale [10]" value="<nil>"
```

Any other thoughts/opinions?

**Comment by MatthewHink** [comment]
The reason for the nil reading came about due to not getting a reading on specific thermistors on the i2c bus. Previously we were erroring out the entire bulk read, even for thermistors where we got a reading.

Is there a need to do a transform on a reading we did not get in the first place?

**Comment by edaniszewski** [comment]
Yeah, thats along the lines of what I was thinking.

I'll  update the issue name to track work to make changes to not transform on a nil reading
