### ISSUE TITLE
Info / Type / Context in the reading.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-sdk#475]
This came up during planning. When reading all devices, the GUID is in the reading, but not info / context / type.

We should have enough information in the reading so that when we curl read to read all devices we can tell what device is what.

**Comment by edaniszewski** [comment]
```json
  {
    "device": "65032c4b-4730-530b-95f8-a0c1abc47b1f",
    "timestamp": "2020-08-11T12:54:35Z",
    "type": "voltage",
    "device_type": "voltage",
    "unit": {
      "name": "volt",
      "symbol": "V"
    },
    "value": 283.0,
    "context": {
      "model": "PXGMS UPS + EATON 93PM"
    }
  }
```

the context and the type (both device type (`device_type`) and reading type (`type`)) both appear to be in the reading output. 

Leaving out the info was intentional at  first because I _believe_ at some point there was talk about implementing an "info" specific to readings  with the idea that if there was a  device with lots of different readings, all the readings could specify their own info string as opposed to using the device info string. I think this was from when we  had a single device instance capable of having multiple  sub-devices defined via the device Data

Thats not  really the case  anymore / not something that I  think we are looking for, so I'm good with adding in the device info string into the reading response. Will be helpful to more easily identify readings/the devices which they originate from.

**Comment by MatthewHink** [comment]
It looks like we do have most of what we need there. Below are some examples of why info would be useful.

```
  {
    "device": "4f05aad8-e50c-55ad-b8b5-6963cd7b8c7c",
    "timestamp": "2020-08-13T16:27:23Z",
    "type": "state",
    "device_type": "switch",
    "unit": null,
    "value": true,
    "context": {
      "model": "pCOWeb"
    }
  },

  {
    "device": "5f220818-8cdf-5712-91d8-e46bdf8ca200",
    "timestamp": "2020-08-13T16:27:24Z",
    "type": "current",
    "device_type": "current",
    "unit": {
      "name": "ampere",
      "symbol": "A"
    },
    "value": 0.20614095032215118,
    "context": {
      "zone": "3",
      "rack": "w1",
      "model": "EG4015"
    }
  },

  {
    "device": "c3c82ca1-f181-5597-9a89-6f4ecdde8c66",
    "timestamp": "2020-08-13T16:27:24Z",
    "type": "power",
    "device_type": "power",
    "unit": {
      "name": "watt",
      "symbol": "W"
    },
    "value": 0.0,
    "context": {
      "model": "EG4015",
      "zone": "1",
      "rack": "w6"
    }
  },
  {
    "device": "b8079494-4241-5038-97e0-7642d27df616",
    "timestamp": "2020-08-13T16:27:24Z",
    "type": "frequency",
    "device_type": "frequency",
    "unit": {
      "name": "hertz",
      "symbol": "Hz"
    },
    "value": 60.00756072998047,
    "context": {
      "model": "EG4015",
      "rack": "w1"
    }
  },

  {
    "device": "d0197f9d-9806-5d0d-9ddb-4c4e90b05358",
    "timestamp": "2020-08-13T16:27:24Z",
    "type": "energy",
    "device_type": "power",
    "unit": {
      "name": "kilowatt-hour",
      "symbol": "kWh"
    },
    "value": -6740.378247614524,
    "context": {
      "model": "EG4015",
      "zone": "2",
      "rack": "w3"
    }
  },
```

**Comment by MatthewHink** [comment]
@edaniszewski What will it take to get the info in the reading? This is a huge problem on /read and /read (single device) from a debugging perspective.

**Comment by edaniszewski** [comment]
I was thinking a similar thing this past week, I think its high time we add the info into the device reading. I'll see what it will take. From a code perspective, I don't think it would be much, but there would need to be a change in the gRPC protobuf definition, so that may complicate things.

**Comment by edaniszewski** [comment]
@MatthewHink have the updates in the synse-grpc repo here: https://github.com/vapor-ware/synse-server-grpc/pull/68

Locally, I updated and tested the SDK with those changes and it looks like its super easy to update and will not be a breaking change to the internal gRPC API.

Once thats merged in, I'll cut a new release, open a PR to update the SDK, and then work on updating Synse Server. After that is all in place, we can cut new releases and slow roll the changes out to Synse plugins.
